name: rust_ci_build
on:
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: rust_build_test
    runs-on: self-hosted
    container:
      image: rust
    steps:
      - uses: actions/checkout@v3
      - name: Install clippy and rustfmt
        run: |
          rustup component add clippy
          rustup component add rustfmt
      - name: Check build
        run: cd ./rokim_todo && cargo check
      - name: Run fmt
        run: cd ./rokim_todo && cargo fmt -- --check
      - name: Run clippy
        run: cd ./rokim_todo && cargo clippy -- -D warnings
      - name: Run tests
        run: cd ./rokim_todo && cargo test
